# Generated by Django 5.1.6 on 2025-03-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menutype_dish_is_special_category_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='menu_type',
            field=models.CharField(choices=[('main', 'Основное меню'), ('bar', 'Барное меню')], default='main', max_length=10),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['menu_type', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'menu_type')},
        ),
        migrations.DeleteModel(
            name='MenuType',
        ),
    ]
