# Generated by Django 5.1.6 on 2025-03-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_menu_type_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_special',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='order',
        ),
    ]
